// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRYAyqlnHmecqfj1uIYtq73EhPqTOEVp0',
    appId: '1:884479623105:web:f11aaa188077b58a5e3940',
    messagingSenderId: '884479623105',
    projectId: 'arkanstoreapp-ffe12',
    authDomain: 'arkanstoreapp-ffe12.firebaseapp.com',
    storageBucket: 'arkanstoreapp-ffe12.appspot.com',
    measurementId: 'G-LCQW52BQD5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPz7_mcdubxsrxcCF8u9SxBH7y85cVZes',
    appId: '1:884479623105:android:14f129d6e7d0f85d5e3940',
    messagingSenderId: '884479623105',
    projectId: 'arkanstoreapp-ffe12',
    storageBucket: 'arkanstoreapp-ffe12.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBF1XFPlV_5-ydJFKSQN1hCsaEXN6xoLRY',
    appId: '1:884479623105:ios:97ba10015a2c4c6b5e3940',
    messagingSenderId: '884479623105',
    projectId: 'arkanstoreapp-ffe12',
    storageBucket: 'arkanstoreapp-ffe12.appspot.com',
    iosBundleId: 'com.example.arkanstoreApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBF1XFPlV_5-ydJFKSQN1hCsaEXN6xoLRY',
    appId: '1:884479623105:ios:97ba10015a2c4c6b5e3940',
    messagingSenderId: '884479623105',
    projectId: 'arkanstoreapp-ffe12',
    storageBucket: 'arkanstoreapp-ffe12.appspot.com',
    iosBundleId: 'com.example.arkanstoreApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRYAyqlnHmecqfj1uIYtq73EhPqTOEVp0',
    appId: '1:884479623105:web:5a81caa61aa5d97a5e3940',
    messagingSenderId: '884479623105',
    projectId: 'arkanstoreapp-ffe12',
    authDomain: 'arkanstoreapp-ffe12.firebaseapp.com',
    storageBucket: 'arkanstoreapp-ffe12.appspot.com',
    measurementId: 'G-8PFEHW2156',
  );

}